name: Robot Framework

on:
  push:
    branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: https://github.com/mrlcast/Robot-Framework-Intranet/cadastro
            ROBOT_REPORTS_DIR: https://github.com/mrlcast/Robot-Framework-Intranet/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: https://github.com/mrlcast/Robot-Framework-Intranet/reports
